// ── Brandaro logo resolution chain ────────────────────────────────────────
// Priority:
//   1. A Google Places photo that looks like a logo (square-ish, small, no
//      user attribution — i.e. owner-supplied profile art).
//   2. Ideogram generation via IDEOGRAM_API_KEY.
//   3. null — brandaro-base already renders a typographic fallback.
//
// Never throws. A failed chain returns { url: null, source: "none" } so demo
// generation continues untouched.

export interface LogoCandidatePhoto {
  url: string;
  width?: number | null;
  height?: number | null;
  attribution?: string | null;
}

export interface LogoResult {
  url: string | null;
  source: "places_photo" | "ideogram" | "none";
  error?: string;
}

const LOGO_BUCKET = "brandaro-logos";
const SIGNED_URL_TTL = 60 * 60 * 24 * 365 * 10; // 10 years

/**
 * Step 1 — heuristic logo detection over already-fetched Places photos.
 * Places API (New) does not expose a "logo" category, so we approximate it:
 * a logo is near-square, modest resolution, and has no third-party author
 * attribution (owner/profile art rather than a customer snapshot).
 */
export function pickLogoLikePhoto(
  photos: LogoCandidatePhoto[] | null | undefined,
): string | null {
  if (!Array.isArray(photos) || photos.length === 0) return null;

  const scored = photos
    .map((p) => {
      const w = Number(p?.width) || 0;
      const h = Number(p?.height) || 0;
      if (!p?.url || !w || !h) return null;
      const ratio = w / h;
      const squareish = ratio >= 0.85 && ratio <= 1.18;
      if (!squareish) return null;
      // Logos are rarely huge photographic captures.
      if (Math.max(w, h) > 1200) return null;
      const ownerish = !p.attribution;
      return { url: p.url, score: (ownerish ? 2 : 0) + (Math.max(w, h) <= 800 ? 1 : 0) };
    })
    .filter(Boolean) as { url: string; score: number }[];

  if (!scored.length) return null;
  scored.sort((a, b) => b.score - a.score);
  // Require at least one positive signal beyond being square.
  return scored[0].score > 0 ? scored[0].url : null;
}

/**
 * Step 2 — Ideogram generation. Returns raw PNG bytes, or null on any
 * failure (missing key, 402 billing, 429 rate limit, timeout, bad body).
 */
export async function generateIdeogramLogo(opts: {
  business_name: string;
  industry: string;
  color_primary?: string | null;
  color_secondary?: string | null;
  timeoutMs?: number;
}): Promise<{ bytes: Uint8Array | null; error?: string }> {
  const apiKey = Deno.env.get("IDEOGRAM_API_KEY");
  if (!apiKey) return { bytes: null, error: "missing_ideogram_key" };

  const primary = opts.color_primary || "#111111";
  const secondary = opts.color_secondary || "#666666";
  const prompt =
    `modern, professional logo for a ${opts.industry} business called ` +
    `${opts.business_name}, using colors ${primary} and ${secondary}, ` +
    `clean and simple, no text unless it's the business initial`;

  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), opts.timeoutMs ?? 45_000);
  try {
    const form = new FormData();
    form.append("prompt", prompt);
    form.append("aspect_ratio", "1x1");
    form.append("rendering_speed", "DEFAULT");
    form.append("style_type", "DESIGN");

    const res = await fetch("https://api.ideogram.ai/v1/ideogram-v3/generate", {
      method: "POST",
      headers: { "Api-Key": apiKey },
      body: form,
      signal: controller.signal,
    });

    if (!res.ok) {
      const body = await res.text().catch(() => "");
      return { bytes: null, error: `ideogram_${res.status}:${body.slice(0, 200)}` };
    }

    const json = await res.json().catch(() => null);
    const imageUrl = json?.data?.[0]?.url;
    if (!imageUrl) return { bytes: null, error: "ideogram_no_image_url" };

    const img = await fetch(imageUrl, { signal: controller.signal });
    if (!img.ok) return { bytes: null, error: `ideogram_download_${img.status}` };
    return { bytes: new Uint8Array(await img.arrayBuffer()) };
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    return { bytes: null, error: `ideogram_exception:${msg.slice(0, 200)}` };
  } finally {
    clearTimeout(timer);
  }
}

/** Persist generated bytes to the private logo bucket and return a long-lived signed URL. */
async function storeLogo(
  supabase: any,
  demoIdOrSlug: string,
  bytes: Uint8Array,
): Promise<{ url: string | null; error?: string }> {
  const path = `${demoIdOrSlug}/logo.png`;
  const up = await supabase.storage
    .from(LOGO_BUCKET)
    .upload(path, bytes, { contentType: "image/png", upsert: true });
  if (up.error) return { url: null, error: `storage_upload:${up.error.message}` };

  const signed = await supabase.storage
    .from(LOGO_BUCKET)
    .createSignedUrl(path, SIGNED_URL_TTL);
  if (signed.error || !signed.data?.signedUrl) {
    return { url: null, error: `storage_sign:${signed.error?.message ?? "no_url"}` };
  }
  return { url: signed.data.signedUrl };
}

/**
 * Full chain. Always resolves; never throws.
 * Writes nothing to the database — the caller owns persistence.
 */
export async function resolveLogoUrl(
  supabase: any,
  opts: {
    demo_id: string;
    business_name: string;
    industry: string;
    photos?: LogoCandidatePhoto[] | null;
    color_primary?: string | null;
    color_secondary?: string | null;
  },
): Promise<LogoResult> {
  // 1) Places photo that looks like a logo.
  const placesLogo = pickLogoLikePhoto(opts.photos);
  if (placesLogo) {
    console.log("[logo] using places photo as logo");
    return { url: placesLogo, source: "places_photo" };
  }

  // 2) Ideogram.
  const gen = await generateIdeogramLogo({
    business_name: opts.business_name,
    industry: opts.industry,
    color_primary: opts.color_primary,
    color_secondary: opts.color_secondary,
  });
  if (!gen.bytes) {
    console.warn("[logo] ideogram unavailable:", gen.error);
    return { url: null, source: "none", error: gen.error };
  }

  const stored = await storeLogo(supabase, opts.demo_id, gen.bytes);
  if (!stored.url) {
    console.warn("[logo] storage failed:", stored.error);
    return { url: null, source: "none", error: stored.error };
  }

  console.log("[logo] generated via ideogram");
  return { url: stored.url, source: "ideogram" };
}
