import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import { supabase } from "@/integrations/supabase/client";
import { VANewLeadIntakeForm } from "@/components/va/VANewLeadIntakeForm";
import { Loader2, AlertCircle } from "lucide-react";

/**
 * Public, token-gated Brandaro discovery intake.
 * Route: /auth/intake/:token
 * Reached only via the SMS/email link generated by va-send-intake-invite.
 */
export default function PublicIntakePage() {
  const { token } = useParams<{ token: string }>();
  const [state, setState] = useState<"loading" | "ok" | "invalid" | "submitted">("loading");
  const [prefill, setPrefill] = useState<any>(null);

  useEffect(() => {
    if (!token) { setState("ok"); return; }
    (async () => {
      const { data, error } = await supabase.rpc("get_public_intake_invite", { _token: token });
      const row = Array.isArray(data) ? data[0] : data;
      if (error || !row) { setState("invalid"); return; }
      if (row.submitted_at) { setState("submitted"); return; }
      setPrefill({
        businessName: row.business_name || "",
        ownerName: row.owner_name || "",
        email: row.email || "",
        phone: row.phone || "",
      });
      setState("ok");
    })();
  }, [token]);

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 py-10 px-4">
      <div className="max-w-4xl mx-auto">
        <div className="mb-8 text-center">
          <h1 className="text-3xl sm:text-4xl font-bold text-white">Brandaro Digital — Project Intake</h1>
          <p className="mt-2 text-sm text-slate-400">Complete this discovery form so our team can scope your project.</p>
        </div>

        {state === "loading" && (
          <div className="flex items-center justify-center py-20 text-slate-400">
            <Loader2 className="h-6 w-6 animate-spin mr-2" /> Loading your intake form...
          </div>
        )}

        {state === "invalid" && (
          <div className="rounded-2xl border border-red-500/30 bg-red-500/5 p-8 text-center">
            <AlertCircle className="mx-auto h-10 w-10 text-red-400 mb-3" />
            <h2 className="text-xl font-bold text-white">Invalid or expired link</h2>
            <p className="mt-2 text-sm text-slate-400">Please request a new intake link from your Brandaro contact.</p>
          </div>
        )}

        {state === "submitted" && (
          <div className="rounded-2xl border border-cyan-500/30 bg-slate-900/60 p-10 text-center">
            <h2 className="text-2xl font-bold text-white">This intake has already been submitted</h2>
            <p className="mt-2 text-sm text-slate-400">Thanks — our team will be in touch shortly.</p>
          </div>
        )}

        {state === "ok" && (
          <VANewLeadIntakeForm mode="public" inviteToken={token} initialPrefill={prefill} />
        )}
      </div>
    </div>
  );
}
