import {
  MapPin, Package, Users, TrendingUp, FileText, Phone, MessageCircle, Mail,
  BarChart3, Map, Radar, Brain, Target, DollarSign, Trophy, Gift, Home, Settings,
  Database, Crown, Truck, Bike, ClipboardCheck, CreditCard, FileSpreadsheet,
  Scale, Search, Briefcase, Building2, Calculator
} from 'lucide-react';

export const navigationItems = [
  { to: '/', icon: MapPin, label: 'Dashboard', roles: ['admin', 'driver', 'biker', 'clerk'] },
  
  // 🌍 Territory Intelligence (Floor 0)
  { to: '/territory', icon: Map, label: '🌍 Territory Control', roles: ['admin', 'ceo'] },
  { to: '/territory/gap-intelligence', icon: Radar, label: 'Gap Intelligence', roles: ['admin', 'ceo'] },
  { to: '/territory/ingestion', icon: Database, label: 'Ingestion Wizard', roles: ['admin'] },
  { to: '/territory/planning', icon: Target, label: 'Strategic Planning', roles: ['admin', 'ceo'] },
  { to: '/territory/planning/history', icon: FileText, label: 'Planning History', roles: ['admin', 'ceo'] },
  { to: '/territory/ai-permissions', icon: Settings, label: 'AI Permissions', roles: ['admin'] },
  { to: '/territory/ai-permissions/neighborhoods', icon: Map, label: 'AI Neighborhood Perms', roles: ['admin'] },
  { to: '/territory/ai-permissions/actions', icon: Settings, label: 'AI Action Perms', roles: ['admin'] },
  { to: '/territory/ai-violations', icon: Database, label: '🛡️ AI Violations', roles: ['admin'] },
  { to: '/territory/ai-review-queue', icon: Database, label: '👁️ AI Review Queue', roles: ['admin'] },
  { to: '/territory/playbooks', icon: Database, label: '📖 Playbooks', roles: ['admin'] },

  // 📊 Exports (Floor 1–9)
  { to: '/grabba/export/command', icon: FileSpreadsheet, label: '🔥 Command Export', roles: ['admin'] },
  { to: '/grabba/export/floor1', icon: FileSpreadsheet, label: '🏢 CRM Export', roles: ['admin'] },
  { to: '/grabba/export/floor2', icon: FileSpreadsheet, label: '📞 Comms Export', roles: ['admin'] },
  { to: '/grabba/export/floor3', icon: FileSpreadsheet, label: '📦 Inventory Export', roles: ['admin'] },
  { to: '/grabba/export/floor4', icon: FileSpreadsheet, label: '🚴 Delivery Export', roles: ['admin'] },
  { to: '/grabba/export/floor5', icon: FileSpreadsheet, label: '📑 Orders Export', roles: ['admin'] },
  { to: '/grabba/export/floor6', icon: FileSpreadsheet, label: '🏭 Production Export', roles: ['admin'] },
  { to: '/grabba/export/floor7', icon: FileSpreadsheet, label: '🏬 Wholesale Export', roles: ['admin'] },
  { to: '/grabba/export/floor8', icon: FileSpreadsheet, label: '🤝 Ambassadors Export', roles: ['admin'] },
  { to: '/grabba/export/floor9', icon: FileSpreadsheet, label: '🤖 AI Ops Export', roles: ['admin'] },

  // Floor 1+
  { to: '/system-operations/ai-ceo-control-room', icon: Crown, label: 'CEO Command Center', roles: ['ceo'], premium: true },
  { to: '/stores', icon: Package, label: 'Stores', roles: ['admin', 'driver'] },
  { to: '/routes', icon: MapPin, label: 'Routes', roles: ['admin', 'driver'] },
  { to: '/map', icon: Map, label: 'Live Map', roles: ['admin', 'driver', 'csr'] },
  { to: '/batch-import', icon: Package, label: 'Batch Import', roles: ['admin'] },
  { to: '/wholesale', icon: Package, label: 'Wholesale', roles: ['admin', 'csr'] },
  { to: '/wholesale/marketplace', icon: Package, label: 'Marketplace', roles: ['admin'] },
  { to: '/influencers', icon: Users, label: 'Influencers', roles: ['admin'] },
  { to: '/influencers/campaigns', icon: Package, label: 'Campaigns', roles: ['admin'] },
  { to: '/missions', icon: Target, label: 'Missions', roles: ['admin', 'driver', 'biker'] },
  { to: '/missions-hq', icon: Target, label: 'Missions HQ', roles: ['admin'] },
  { to: '/crm', icon: Users, label: 'CRM', roles: ['admin', 'csr'] },
  { to: '/crm/data', icon: Database, label: 'Data Management', roles: ['admin', 'csr'] },
  { to: '/templates', icon: FileText, label: 'Templates', roles: ['admin'] },
  { to: '/territories', icon: Map, label: 'Territories', roles: ['admin', 'csr'] },
  { to: '/analytics/revenue-brain', icon: Brain, label: 'Revenue Brain', roles: ['admin'] },
  { to: '/ops/opportunity-radar', icon: Radar, label: 'Opportunity Radar', roles: ['admin', 'csr'] },
  { to: '/opportunities', icon: Target, label: 'All Opportunities', roles: ['admin', 'csr', 'va'] },
  { to: '/ai/meta', icon: Brain, label: 'Meta-AI Supervisor', roles: ['admin'] },
  { to: '/expansion/regions', icon: MapPin, label: 'Territory Regions', roles: ['admin'] },
  { to: '/expansion/heatmap', icon: Map, label: 'Expansion Heatmap', roles: ['admin'] },
  { to: '/ambassadors/regions', icon: Users, label: 'Regional Ambassadors', roles: ['admin'] },
  { to: '/stores/order', icon: Package, label: 'Place Order', roles: ['admin', 'csr'] },
  { to: '/wholesale/fulfillment', icon: Package, label: 'Fulfillment', roles: ['admin', 'csr'] },
  { to: '/billing', icon: DollarSign, label: 'Billing', roles: ['admin'] },
  { to: '/analytics/economics', icon: TrendingUp, label: 'Economic Analytics', roles: ['admin'] },
  { to: '/payouts/ambassadors', icon: Users, label: 'Ambassador Payouts', roles: ['admin'] },
  { to: '/payouts/bikers', icon: Package, label: 'Biker Payouts', roles: ['admin'] },
  { to: '/sales', icon: Target, label: 'Sales Dashboard', roles: ['admin', 'csr'] },
  { to: '/sales/prospects', icon: Users, label: 'Prospects', roles: ['admin', 'csr'] },
  { to: '/sales/report', icon: BarChart3, label: 'Sales Report', roles: ['admin', 'csr'] },
  
  // Delivery & Logistics
  { to: '/delivery', icon: Truck, label: 'Delivery Dashboard', roles: ['admin', 'dispatcher', 'ops_manager'] },
  { to: '/biker/home', icon: Bike, label: 'Biker OS', roles: ['admin', 'dispatcher', 'ops_manager', 'biker'] },
  { to: '/delivery/deliveries', icon: Package, label: 'Deliveries Board', roles: ['admin', 'dispatcher', 'ops_manager'] },
  { to: '/delivery/drivers', icon: Truck, label: 'Drivers', roles: ['admin', 'dispatcher', 'ops_manager'] },
  { to: '/delivery/bikers', icon: Bike, label: 'Bikers', roles: ['admin', 'dispatcher', 'ops_manager'] },
  { to: '/delivery/biker-tasks', icon: ClipboardCheck, label: 'Store Checks', roles: ['admin', 'dispatcher', 'ops_manager', 'biker'] },
  { to: '/delivery/locations', icon: MapPin, label: 'Locations', roles: ['admin', 'dispatcher', 'ops_manager'] },
  { to: '/delivery/payouts', icon: CreditCard, label: 'Worker Payouts', roles: ['admin', 'finance', 'ops_manager'] },
  { to: '/delivery/debt', icon: DollarSign, label: 'Debt Collection', roles: ['admin', 'finance'] },
  { to: '/delivery/driver-home', icon: Home, label: 'Driver Home', roles: ['driver', 'admin', 'employee'] },
  { to: '/delivery/my-route', icon: MapPin, label: 'My Route', roles: ['driver', 'admin', 'employee'] },
  
  { to: '/me/home', icon: MapPin, label: 'Worker Home', roles: ['driver', 'biker', 'ambassador'] },
  { to: '/me/driver', icon: Home, label: 'Driver Dashboard', roles: ['driver', 'biker'] },
  { to: '/drivers/leaderboard', icon: Trophy, label: 'Leaderboard', roles: ['driver', 'biker', 'admin'] },
  { to: '/rewards', icon: Gift, label: 'Rewards', roles: ['driver', 'biker'] },
  { to: '/drivers/payroll', icon: DollarSign, label: 'Payroll', roles: ['admin'] },
  { to: '/team', icon: Users, label: 'Team', roles: ['admin'] },
  { to: '/products', icon: Package, label: 'Products', roles: ['admin'] },
  { to: '/analytics', icon: TrendingUp, label: 'Analytics', roles: ['admin', 'accountant'] },
  { to: '/training', icon: Package, label: 'Training', roles: ['admin', 'csr', 'driver', 'biker', 'ambassador'] },
  { to: '/settings/automation', icon: Settings, label: 'Automation', roles: ['admin'] },

  // 💰 Surplus Funds OS
  { to: '/surplus-funds', icon: Scale, label: '💰 Surplus Funds OS', roles: ['admin', 'ceo'] },
  { to: '/surplus-funds/leads', icon: FileText, label: 'Floor 1 — Lead Intelligence', roles: ['admin', 'ceo'] },
  { to: '/surplus-funds/campaigns', icon: Phone, label: 'Floor 2 — DC Campaigns', roles: ['admin'] },
  { to: '/surplus-funds/cases', icon: Briefcase, label: 'Floor 3 — Case Management', roles: ['admin', 'ceo'] },
  { to: '/surplus-funds/attorneys', icon: Scale, label: 'Floor 4 — Attorney Network', roles: ['admin'] },
  { to: '/surplus-funds/documents', icon: FileText, label: 'Floor 5 — Documents', roles: ['admin'] },
  { to: '/surplus-funds/automation', icon: Settings, label: 'Floor 6 — AI & Automation', roles: ['admin'] },
  { to: '/surplus-funds/analytics', icon: TrendingUp, label: 'Floor 7 — Analytics', roles: ['admin', 'ceo'] },

  // 🏠 Real Estate OS
  { to: '/real-estate', icon: Building2, label: '🏠 Real Estate OS', roles: ['admin', 'ceo', 'va'] },
  { to: '/real-estate/leads', icon: Target, label: 'Floor 1 — Lead Intelligence', roles: ['admin', 'ceo'] },
  { to: '/real-estate/campaigns', icon: Phone, label: 'Floor 2 — DC Campaigns', roles: ['admin'] },
  { to: '/real-estate/deals', icon: FileText, label: 'Floor 3 — Active Deals', roles: ['admin', 'ceo'] },
  { to: '/real-estate/buyers', icon: Building2, label: 'Floor 4 — Buyer Network', roles: ['admin', 'ceo'] },
  { to: '/real-estate/va-desk', icon: Users, label: 'Floor 5 — VA Desk', roles: ['admin', 'va'] },
  { to: '/real-estate/analyzer', icon: Calculator, label: 'Floor 6 — Deal Analyzer', roles: ['admin', 'ceo'] },
  { to: '/real-estate/automation', icon: Brain, label: 'Floor 7 — Automation Engine', roles: ['admin'] },
  { to: '/real-estate/markets', icon: Map, label: 'Floor 8 — Market Intelligence', roles: ['admin', 'ceo'] },
  { to: '/real-estate/analytics', icon: TrendingUp, label: 'Floor 9 — Analytics', roles: ['admin', 'ceo'] },
];
