import {
  MapPin, Package, Users, TrendingUp, FileText, Phone, MessageCircle, Mail,
  BarChart3, Map, Radar, Brain, Target, DollarSign, Trophy, Gift, Home, Settings,
  Database, Crown
} from 'lucide-react';

export const navigationItems = [
  { to: '/', icon: MapPin, label: 'Dashboard', roles: ['admin', 'driver', 'biker', 'clerk'] },
  { to: '/system-operations/ai-ceo-control-room', icon: Crown, label: 'CEO Command Center', roles: ['ceo'], premium: true },
  { to: '/stores', icon: Package, label: 'Stores', roles: ['admin', 'driver'] },
  { to: '/routes', icon: MapPin, label: 'Routes', roles: ['admin', 'driver'] },
  { to: '/map', icon: Map, label: 'Live Map', roles: ['admin', 'driver', 'csr'] },
  { to: '/batch-import', icon: Package, label: 'Batch Import', roles: ['admin'] },
  { to: '/wholesale', icon: Package, label: 'Wholesale', roles: ['admin', 'csr'] },
  { to: '/wholesale/marketplace', icon: Package, label: 'Marketplace', roles: ['admin'] },
  { to: '/influencers', icon: Users, label: 'Influencers', roles: ['admin'] },
  { to: '/influencers/campaigns', icon: Package, label: 'Campaigns', roles: ['admin'] },
  { to: '/missions', icon: Target, label: 'Missions', roles: ['admin', 'driver', 'biker'] },
  { to: '/missions-hq', icon: Target, label: 'Missions HQ', roles: ['admin'] },
  { to: '/crm', icon: Users, label: 'CRM', roles: ['admin', 'csr'] },
  { to: '/crm/data', icon: Database, label: 'Data Management', roles: ['admin', 'csr'] },
  { to: '/templates', icon: FileText, label: 'Templates', roles: ['admin'] },
  { to: '/territories', icon: Map, label: 'Territories', roles: ['admin', 'csr'] },
  { to: '/analytics/revenue-brain', icon: Brain, label: 'Revenue Brain', roles: ['admin'] },
  { to: '/ops/opportunity-radar', icon: Radar, label: 'Opportunity Radar', roles: ['admin', 'csr'] },
  { to: '/ai/meta', icon: Brain, label: 'Meta-AI Supervisor', roles: ['admin'] },
  { to: '/expansion/regions', icon: MapPin, label: 'Territory Regions', roles: ['admin'] },
  { to: '/expansion/heatmap', icon: Map, label: 'Expansion Heatmap', roles: ['admin'] },
  { to: '/ambassadors/regions', icon: Users, label: 'Regional Ambassadors', roles: ['admin'] },
  { to: '/stores/order', icon: Package, label: 'Place Order', roles: ['admin', 'csr'] },
  { to: '/wholesale/fulfillment', icon: Package, label: 'Fulfillment', roles: ['admin', 'csr'] },
  { to: '/billing', icon: DollarSign, label: 'Billing', roles: ['admin'] },
  { to: '/analytics/economics', icon: TrendingUp, label: 'Economic Analytics', roles: ['admin'] },
  { to: '/payouts/ambassadors', icon: Users, label: 'Ambassador Payouts', roles: ['admin'] },
  { to: '/payouts/bikers', icon: Package, label: 'Biker Payouts', roles: ['admin'] },
  { to: '/sales', icon: Target, label: 'Sales Dashboard', roles: ['admin', 'csr'] },
  { to: '/sales/prospects', icon: Users, label: 'Prospects', roles: ['admin', 'csr'] },
  { to: '/sales/report', icon: BarChart3, label: 'Sales Report', roles: ['admin', 'csr'] },
  { to: '/me/home', icon: MapPin, label: 'Worker Home', roles: ['driver', 'biker', 'ambassador'] },
  { to: '/me/driver', icon: Home, label: 'Driver Dashboard', roles: ['driver', 'biker'] },
  { to: '/drivers/leaderboard', icon: Trophy, label: 'Leaderboard', roles: ['driver', 'biker', 'admin'] },
  { to: '/rewards', icon: Gift, label: 'Rewards', roles: ['driver', 'biker'] },
  { to: '/drivers/payroll', icon: DollarSign, label: 'Payroll', roles: ['admin'] },
  { to: '/team', icon: Users, label: 'Team', roles: ['admin'] },
  { to: '/products', icon: Package, label: 'Products', roles: ['admin'] },
  { to: '/analytics', icon: TrendingUp, label: 'Analytics', roles: ['admin', 'accountant'] },
  { to: '/training', icon: Package, label: 'Training', roles: ['admin', 'csr', 'driver', 'biker', 'ambassador'] },
  { to: '/settings/automation', icon: Settings, label: 'Automation', roles: ['admin'] },
];
