// Dynasty Direct Pro — monthly report cron
// Runs first of each month at 9am UTC. For each active Pro subscriber,
// computes inventory analytics and emails the store the report via Resend.
import { createClient } from "npm:@supabase/supabase-js@2.57.2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

const GATEWAY_URL = "https://connector-gateway.lovable.dev/resend";

function fmt(n: number) {
  return `$${Number(n || 0).toLocaleString(undefined, { maximumFractionDigits: 2 })}`;
}

function buildHtml(storeName: string, monthLabel: string, a: any) {
  const topSellers = (a?.top_sellers ?? []).map((t: any, i: number) =>
    `<tr><td>${i + 1}</td><td>${t.product_name}</td><td align="right">${t.units_sold_30d}</td><td align="right">${fmt(t.revenue_30d)}</td><td align="right">${t.stock_left}</td></tr>`
  ).join("");
  const alerts = (a?.reorder_alerts ?? []).map((r: any) =>
    `<li><b>${r.product_name}</b> — ${r.alert_message}</li>`
  ).join("") || "<li>No reorder alerts</li>";
  return `
  <div style="font-family: -apple-system, sans-serif; max-width: 640px; margin: 0 auto; padding: 24px;">
    <h1>📊 Dynasty Direct Pro — Monthly Report</h1>
    <p style="color:#666">${storeName} · ${monthLabel}</p>
    <h2>Summary</h2>
    <ul>
      <li>Total stock value: <b>${fmt(a?.total_inventory_value ?? 0)}</b></li>
      <li>Total retail value: <b>${fmt(a?.total_retail_value ?? 0)}</b></li>
      <li>Potential profit: <b>${fmt((a?.total_retail_value ?? 0) - (a?.total_inventory_value ?? 0))}</b></li>
    </ul>
    <h2>Top 10 Sellers (last 30 days)</h2>
    <table cellpadding="6" cellspacing="0" border="1" style="border-collapse:collapse;width:100%">
      <thead><tr><th>#</th><th>Product</th><th>Sold</th><th>Revenue</th><th>Stock</th></tr></thead>
      <tbody>${topSellers || "<tr><td colspan='5'>No sales data yet</td></tr>"}</tbody>
    </table>
    <h2>Reorder Recommendations</h2>
    <ul>${alerts}</ul>
    <p style="color:#888;font-size:12px;margin-top:32px">Generated by Dynasty Direct Pro · Reply to this email for support.</p>
  </div>`;
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  const supabase = createClient(
    Deno.env.get("SUPABASE_URL") ?? "",
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "",
    { auth: { persistSession: false } }
  );

  const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
  const RESEND_API_KEY = Deno.env.get("RESEND_API_KEY");

  try {
    const { data: subs, error } = await supabase
      .from("dd_pro_subscriptions")
      .select("id, store_account_id")
      .in("status", ["trial", "active"]);
    if (error) throw error;

    const monthLabel = new Date().toLocaleString("en-US", { month: "long", year: "numeric" });
    let sent = 0;
    let skipped = 0;
    const errors: string[] = [];

    for (const sub of subs ?? []) {
      if (!sub.store_account_id) { skipped++; continue; }
      try {
        const { data: store } = await supabase
          .from("store_accounts")
          .select("business_name,email")
          .eq("id", sub.store_account_id)
          .maybeSingle();
        if (!store?.email) { skipped++; continue; }

        const { data: analytics } = await supabase.rpc("dd_store_inventory_analytics", { p_store_id: sub.store_account_id });
        const html = buildHtml(store.business_name ?? "Your Store", monthLabel, analytics);

        if (LOVABLE_API_KEY && RESEND_API_KEY) {
          const r = await fetch(`${GATEWAY_URL}/emails`, {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
              Authorization: `Bearer ${LOVABLE_API_KEY}`,
              "X-Connection-Api-Key": RESEND_API_KEY,
            },
            body: JSON.stringify({
              from: "Dynasty Direct Pro <onboarding@resend.dev>",
              to: [store.email],
              subject: `Your Dynasty Direct Pro Monthly Report — ${monthLabel}`,
              html,
            }),
          });
          if (!r.ok) {
            const t = await r.text();
            errors.push(`store ${sub.store_account_id}: ${r.status} ${t.slice(0, 200)}`);
            continue;
          }
          sent++;
        } else {
          // No email creds — enqueue via email_jobs if present
          await supabase.from("email_jobs").insert({
            to_email: store.email,
            template: "dd_pro_monthly_report",
            payload: { html, subject: `Your Dynasty Direct Pro Monthly Report — ${monthLabel}` },
          });
          sent++;
        }
      } catch (e: any) {
        errors.push(`store ${sub.store_account_id}: ${e?.message ?? e}`);
      }
    }

    return new Response(JSON.stringify({ ok: true, sent, skipped, errors }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (e: any) {
    return new Response(JSON.stringify({ ok: false, error: e?.message ?? String(e) }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
