import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { supabase } from "@/integrations/supabase/client";
import { Zap, Loader2, Sparkles } from "lucide-react";
import { toast } from "sonner";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

export default function PODGenerate() {
  const [isGenerating, setIsGenerating] = useState(false);
  const [category, setCategory] = useState<string>("evergreen");
  const [quantity, setQuantity] = useState<number>(10);

  const handleGenerate = async () => {
    setIsGenerating(true);
    try {
      // In a real implementation, this would call an AI edge function
      // For now, we'll create sample designs
      const designsToCreate = Array.from({ length: quantity }, (_, i) => ({
        category,
        title: `AI Generated ${category} Design ${i + 1}`,
        ai_description: `High-quality ${category} print design generated by AI`,
        tags: [category, "ai-generated", "pod"],
        seo_keywords: [category, "print on demand", "design"],
        generated_by_ai: true,
        status: "new",
        variations_created: 0,
        approved_by_va: false,
      }));

      const { error } = await supabase.from("pod_designs").insert(designsToCreate);

      if (error) throw error;

      await supabase.from("pod_ai_logs").insert({
        action: "design_generation",
        metadata: {
          category,
          quantity,
          timestamp: new Date().toISOString(),
        },
      });

      toast.success(`Successfully generated ${quantity} ${category} designs!`);
    } catch (error) {
      console.error("Error generating designs:", error);
      toast.error("Failed to generate designs");
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="min-h-screen p-6 space-y-6">
      <div>
        <h1 className="text-4xl font-bold mb-2">AI Design Generator</h1>
        <p className="text-muted-foreground">Generate print-ready designs with AI</p>
      </div>

      {/* Generator Card */}
      <Card className="max-w-2xl mx-auto">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Sparkles className="h-5 w-5 text-primary" />
            Design Generation Settings
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-6">
          {/* Category Selection */}
          <div className="space-y-2">
            <label className="text-sm font-medium">Design Category</label>
            <Select value={category} onValueChange={setCategory}>
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="evergreen">Evergreen</SelectItem>
                <SelectItem value="holiday">Holiday</SelectItem>
                <SelectItem value="hot_mama">Hot Mama</SelectItem>
                <SelectItem value="gasmask">GasMask</SelectItem>
              </SelectContent>
            </Select>
          </div>

          {/* Quantity Selection */}
          <div className="space-y-2">
            <label className="text-sm font-medium">Quantity to Generate</label>
            <div className="grid grid-cols-3 gap-2">
              {[10, 50, 100].map((qty) => (
                <Button
                  key={qty}
                  variant={quantity === qty ? "default" : "outline"}
                  onClick={() => setQuantity(qty)}
                >
                  {qty} Designs
                </Button>
              ))}
            </div>
          </div>

          {/* Generation Info */}
          <Card className="bg-muted/50">
            <CardContent className="pt-6">
              <div className="space-y-2 text-sm">
                <div className="flex justify-between">
                  <span className="text-muted-foreground">Category:</span>
                  <span className="font-medium">{category}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-muted-foreground">Quantity:</span>
                  <span className="font-medium">{quantity} designs</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-muted-foreground">Output:</span>
                  <span className="font-medium">300 DPI PNG</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-muted-foreground">Sizes:</span>
                  <span className="font-medium">Amazon + Etsy ready</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-muted-foreground">Mockups:</span>
                  <span className="font-medium">Auto-generated</span>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Generate Button */}
          <Button
            onClick={handleGenerate}
            disabled={isGenerating}
            className="w-full"
            size="lg"
          >
            {isGenerating ? (
              <>
                <Loader2 className="mr-2 h-5 w-5 animate-spin" />
                Generating {quantity} Designs...
              </>
            ) : (
              <>
                <Zap className="mr-2 h-5 w-5" />
                Generate {quantity} Designs
              </>
            )}
          </Button>

          {/* AI Info */}
          <div className="text-center text-sm text-muted-foreground">
            <p>Powered by AI • Designs ready in seconds</p>
            <p>Each design includes: PNG file, mockups, SEO data, and descriptions</p>
          </div>
        </CardContent>
      </Card>

      {/* Features Grid */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4 max-w-4xl mx-auto">
        <Card>
          <CardContent className="pt-6 text-center">
            <Zap className="h-8 w-8 mx-auto mb-2 text-primary" />
            <h3 className="font-semibold mb-1">Lightning Fast</h3>
            <p className="text-sm text-muted-foreground">
              Generate 100+ designs in seconds
            </p>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-6 text-center">
            <Sparkles className="h-8 w-8 mx-auto mb-2 text-purple-600" />
            <h3 className="font-semibold mb-1">AI Optimized</h3>
            <p className="text-sm text-muted-foreground">
              SEO keywords and descriptions included
            </p>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-6 text-center">
            <Zap className="h-8 w-8 mx-auto mb-2 text-green-600" />
            <h3 className="font-semibold mb-1">Print Ready</h3>
            <p className="text-sm text-muted-foreground">
              300 DPI, all major marketplace sizes
            </p>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
