import { useEffect, useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { supabase } from "@/integrations/supabase/client";
import { Eye, CheckCircle, XCircle, Settings } from "lucide-react";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";

export default function PODVAControl() {
  const [pendingDesigns, setPendingDesigns] = useState<any[]>([]);
  const [aiLogs, setAiLogs] = useState<any[]>([]);

  useEffect(() => {
    fetchPendingDesigns();
    fetchAILogs();
  }, []);

  const fetchPendingDesigns = async () => {
    try {
      const { data } = await supabase
        .from("pod_designs")
        .select("*")
        .eq("approved_by_va", false)
        .eq("status", "new")
        .order("created_at", { ascending: false });
      setPendingDesigns(data || []);
    } catch (error) {
      console.error("Error fetching pending designs:", error);
    }
  };

  const fetchAILogs = async () => {
    try {
      const { data } = await supabase
        .from("pod_ai_logs")
        .select("*")
        .order("created_at", { ascending: false })
        .limit(10);
      setAiLogs(data || []);
    } catch (error) {
      console.error("Error fetching AI logs:", error);
    }
  };

  const handleApprove = async (designId: string) => {
    try {
      const { error } = await supabase
        .from("pod_designs")
        .update({ approved_by_va: true, status: "queued" })
        .eq("id", designId);

      if (error) throw error;

      toast.success("Design approved!");
      fetchPendingDesigns();
    } catch (error) {
      console.error("Error approving design:", error);
      toast.error("Failed to approve design");
    }
  };

  const handleReject = async (designId: string) => {
    try {
      const { error } = await supabase
        .from("pod_designs")
        .delete()
        .eq("id", designId);

      if (error) throw error;

      toast.success("Design rejected and removed");
      fetchPendingDesigns();
    } catch (error) {
      console.error("Error rejecting design:", error);
      toast.error("Failed to reject design");
    }
  };

  return (
    <div className="min-h-screen p-6 space-y-6">
      <div>
        <h1 className="text-4xl font-bold mb-2">VA Control Panel</h1>
        <p className="text-muted-foreground">Review and manage AI-generated content</p>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <Card>
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-sm font-medium">Pending Review</CardTitle>
            <Eye className="h-4 w-4 text-yellow-600" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{pendingDesigns.length}</div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-sm font-medium">AI Actions Today</CardTitle>
            <Settings className="h-4 w-4 text-blue-600" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{aiLogs.length}</div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-sm font-medium">Automation Status</CardTitle>
            <CheckCircle className="h-4 w-4 text-green-600" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">ON</div>
          </CardContent>
        </Card>
      </div>

      {/* Pending Designs */}
      <Card>
        <CardHeader>
          <CardTitle>Designs Awaiting Approval</CardTitle>
        </CardHeader>
        <CardContent>
          {pendingDesigns.length === 0 ? (
            <div className="text-center py-8 text-muted-foreground">
              No designs pending review
            </div>
          ) : (
            <div className="space-y-4">
              {pendingDesigns.map((design) => (
                <div
                  key={design.id}
                  className="flex items-center justify-between p-4 border rounded-lg"
                >
                  <div>
                    <h3 className="font-medium">{design.title}</h3>
                    <p className="text-sm text-muted-foreground">
                      Category: {design.category} • Generated by AI:{" "}
                      {design.generated_by_ai ? "Yes" : "No"}
                    </p>
                  </div>
                  <div className="flex gap-2">
                    <Button
                      size="sm"
                      variant="default"
                      onClick={() => handleApprove(design.id)}
                    >
                      <CheckCircle className="h-4 w-4 mr-1" />
                      Approve
                    </Button>
                    <Button
                      size="sm"
                      variant="destructive"
                      onClick={() => handleReject(design.id)}
                    >
                      <XCircle className="h-4 w-4 mr-1" />
                      Reject
                    </Button>
                  </div>
                </div>
              ))}
            </div>
          )}
        </CardContent>
      </Card>

      {/* AI Activity Log */}
      <Card>
        <CardHeader>
          <CardTitle>Recent AI Activity</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="space-y-2">
            {aiLogs.map((log) => (
              <div
                key={log.id}
                className="flex items-center justify-between p-3 border-b last:border-0"
              >
                <div>
                  <div className="font-medium">{log.action}</div>
                  <div className="text-xs text-muted-foreground">
                    {new Date(log.created_at).toLocaleString()}
                  </div>
                </div>
              </div>
            ))}
            {aiLogs.length === 0 && (
              <div className="text-center py-4 text-muted-foreground text-sm">
                No AI activity logged yet
              </div>
            )}
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
