export { default as PartnerOverviewTab } from './PartnerOverviewTab';
export { default as PartnerDealsTab } from './PartnerDealsTab';
export { default as PartnerCampaignsTab } from './PartnerCampaignsTab';
export { default as PartnerCommissionsTab } from './PartnerCommissionsTab';
export { default as PartnerInteractionsTab } from './PartnerInteractionsTab';
export { default as PartnerContactsTab } from './PartnerContactsTab';
export { default as PartnerAssetsTab } from './PartnerAssetsTab';
export { default as PartnerNotesTab } from './PartnerNotesTab';
export { default as PartnerMediaVaultTab } from './PartnerMediaVaultTab';
