import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.0";
import { verifiedUpdate } from "../_shared/verifiedMutation.ts";

// One-shot loader: writes the Aug 26 2026 verified state licensing/tier config
// into public.icw_state_config. Every write goes through verifiedUpdate, so a
// row that does not match (or is rejected by policy) throws instead of being
// silently skipped.

const ROWS: Record<string, string>[] = [
  {
    "state": "New York",
    "abbreviation": "NY",
    "tier": "1",
    "priority_rank": "1",
    "snow_vertical": "TRUE",
    "deli_oven_market_density": "HIGH",
    "handyman_license_status": "LOCAL_ONLY",
    "handyman_threshold_usd": "SET_LOCALLY",
    "handyman_city_county_override_notes": "NYC HIC (DCWP) >200; Buffalo; Suffolk/Nassau/Westchester/Putnam/Rockland counties",
    "pest_control_license_required": "Y",
    "pest_control_agency": "NY Dept of Environmental Conservation (DEC)",
    "biohazard_license_required_notes": "N",
    "restoration_threshold_usd": "LOCAL",
    "mold_remediation_specific_license_notes": "Y - assessor, remediation contractor, worker (NYSDOL, Labor Law Art. 32)",
    "confidence": "HIGH"
  },
  {
    "state": "New Jersey",
    "abbreviation": "NJ",
    "tier": "1",
    "priority_rank": "2",
    "snow_vertical": "TRUE",
    "deli_oven_market_density": "HIGH",
    "handyman_license_status": "N_HIC_REGISTRATION",
    "handyman_threshold_usd": "Register w/ Div of Consumer Affairs",
    "handyman_city_county_override_notes": "",
    "pest_control_license_required": "Y",
    "pest_control_agency": "NJ Dept of Environmental Protection",
    "biohazard_license_required_notes": "N",
    "restoration_threshold_usd": "0",
    "mold_remediation_specific_license_notes": "N",
    "confidence": "HIGH"
  },
  {
    "state": "California",
    "abbreviation": "CA",
    "tier": "1",
    "priority_rank": "3",
    "snow_vertical": "FALSE",
    "deli_oven_market_density": "MEDIUM",
    "handyman_license_status": "N_UNDER_THRESHOLD",
    "handyman_threshold_usd": "1000 (raised from 500, AB 2622, eff 1/1/2025)",
    "handyman_city_county_override_notes": "Some cities add HIC permits",
    "pest_control_license_required": "Y",
    "pest_control_agency": "CA Dept of Pesticide Regulation + Structural Pest Control Board",
    "biohazard_license_required_notes": "Y - Trauma Scene Waste Mgmt Practitioner (CDPH)",
    "restoration_threshold_usd": "1000",
    "mold_remediation_specific_license_notes": "N",
    "confidence": "HIGH"
  },
  {
    "state": "Texas",
    "abbreviation": "TX",
    "tier": "1",
    "priority_rank": "4",
    "snow_vertical": "FALSE",
    "deli_oven_market_density": "MEDIUM",
    "handyman_license_status": "N",
    "handyman_threshold_usd": "No state GC/handyman license",
    "handyman_city_county_override_notes": "Houston/Dallas/San Antonio/Austin/Fort Worth registration",
    "pest_control_license_required": "Y",
    "pest_control_agency": "TX Dept of Agriculture, Structural Pest Control Service",
    "biohazard_license_required_notes": "N",
    "restoration_threshold_usd": "0",
    "mold_remediation_specific_license_notes": "Y - assessor & remediator + individual workers (TDLR, Occ. Code Ch 1958; SB 1255 eff 9/1/2025)",
    "confidence": "HIGH"
  },
  {
    "state": "Florida",
    "abbreviation": "FL",
    "tier": "1",
    "priority_rank": "5",
    "snow_vertical": "FALSE",
    "deli_oven_market_density": "MEDIUM",
    "handyman_license_status": "N_STATE_COUNTY",
    "handyman_threshold_usd": "County 500-1000; FS 489.103 1000 exemption",
    "handyman_city_county_override_notes": "Many counties issue Handyman Certificates",
    "pest_control_license_required": "Y",
    "pest_control_agency": "FL Dept of Agriculture & Consumer Services (FDACS)",
    "biohazard_license_required_notes": "Y - Biomedical Waste registration (FL Dept of Health)",
    "restoration_threshold_usd": "1000",
    "mold_remediation_specific_license_notes": "Y - assessor (MRSA) & remediator (MRSR), DBPR, FS 468 Pt XVI",
    "confidence": "HIGH"
  },
  {
    "state": "Illinois",
    "abbreviation": "IL",
    "tier": "1",
    "priority_rank": "6",
    "snow_vertical": "TRUE",
    "deli_oven_market_density": "MEDIUM",
    "handyman_license_status": "LOCAL_ONLY",
    "handyman_threshold_usd": "SET_LOCALLY",
    "handyman_city_county_override_notes": "Chicago Home Repair license",
    "pest_control_license_required": "Y",
    "pest_control_agency": "IL Dept of Agriculture (outdoor) / Dept of Public Health (structural)",
    "biohazard_license_required_notes": "N",
    "restoration_threshold_usd": "LOCAL",
    "mold_remediation_specific_license_notes": "REGISTRATION_PENDING - Mold Remediation Registration Act (410 ILCS 105/PA 103-893), IDPH rules not yet adopted/enforceable",
    "confidence": "HIGH"
  },
  {
    "state": "Pennsylvania",
    "abbreviation": "PA",
    "tier": "1",
    "priority_rank": "7",
    "snow_vertical": "TRUE",
    "deli_oven_market_density": "MEDIUM",
    "handyman_license_status": "N_HIC_REGISTRATION",
    "handyman_threshold_usd": ">5000/yr (register w/ AG)",
    "handyman_city_county_override_notes": "Philadelphia licenses all contractors",
    "pest_control_license_required": "Y",
    "pest_control_agency": "PA Dept of Agriculture",
    "biohazard_license_required_notes": "N",
    "restoration_threshold_usd": "5000",
    "mold_remediation_specific_license_notes": "N",
    "confidence": "HIGH"
  },
  {
    "state": "Georgia",
    "abbreviation": "GA",
    "tier": "1",
    "priority_rank": "8",
    "snow_vertical": "FALSE",
    "deli_oven_market_density": "LOW",
    "handyman_license_status": "DEPENDS",
    "handyman_threshold_usd": "2500",
    "handyman_city_county_override_notes": "County business licenses",
    "pest_control_license_required": "Y",
    "pest_control_agency": "GA Dept of Agriculture / Structural Pest Control Commission",
    "biohazard_license_required_notes": "Y - Trauma Scene Waste Mgmt Practitioner registration",
    "restoration_threshold_usd": "2500",
    "mold_remediation_specific_license_notes": "N",
    "confidence": "HIGH"
  },
  {
    "state": "District of Columbia",
    "abbreviation": "DC",
    "tier": "1",
    "priority_rank": "9",
    "snow_vertical": "TRUE",
    "deli_oven_market_density": "MEDIUM",
    "handyman_license_status": "Y_HIC_LICENSE",
    "handyman_threshold_usd": "ALL_RESIDENTIAL_REPAIR",
    "handyman_city_county_override_notes": "Basic business license also required",
    "pest_control_license_required": "Y",
    "pest_control_agency": "DC Dept of Energy & Environment (DOEE)",
    "biohazard_license_required_notes": "N",
    "restoration_threshold_usd": "0",
    "mold_remediation_specific_license_notes": "Y - assessor & remediator (DOEE)",
    "confidence": "HIGH"
  },
  {
    "state": "North Carolina",
    "abbreviation": "NC",
    "tier": "2",
    "priority_rank": "10",
    "snow_vertical": "FALSE",
    "deli_oven_market_density": "LOW",
    "handyman_license_status": "Y_GC",
    "handyman_threshold_usd": "40000 (N.C. Gen. Stat. Sec 87-1, HB 488, eff 10/1/2023)",
    "handyman_city_county_override_notes": "",
    "pest_control_license_required": "Y",
    "pest_control_agency": "NC Dept of Agriculture & Consumer Services",
    "biohazard_license_required_notes": "N",
    "restoration_threshold_usd": "40000",
    "mold_remediation_specific_license_notes": "N",
    "confidence": "HIGH"
  },
  {
    "state": "Ohio",
    "abbreviation": "OH",
    "tier": "2",
    "priority_rank": "11",
    "snow_vertical": "TRUE",
    "deli_oven_market_density": "LOW",
    "handyman_license_status": "LOCAL_COMM_TRADES_STATE",
    "handyman_threshold_usd": "SET_LOCALLY",
    "handyman_city_county_override_notes": "Cities require registration; state licenses electrical/HVAC/plumbing/hydronics/refrigeration",
    "pest_control_license_required": "Y",
    "pest_control_agency": "OH Dept of Agriculture",
    "biohazard_license_required_notes": "N",
    "restoration_threshold_usd": "LOCAL",
    "mold_remediation_specific_license_notes": "N",
    "confidence": "MEDIUM"
  },
  {
    "state": "Arizona",
    "abbreviation": "AZ",
    "tier": "2",
    "priority_rank": "12",
    "snow_vertical": "FALSE",
    "deli_oven_market_density": "LOW",
    "handyman_license_status": "N_EXEMPT",
    "handyman_threshold_usd": "1000",
    "handyman_city_county_override_notes": "City privilege-tax license",
    "pest_control_license_required": "Y",
    "pest_control_agency": "AZ Dept of Agriculture",
    "biohazard_license_required_notes": "N",
    "restoration_threshold_usd": "1000",
    "mold_remediation_specific_license_notes": "N",
    "confidence": "HIGH"
  },
  {
    "state": "Massachusetts",
    "abbreviation": "MA",
    "tier": "2",
    "priority_rank": "13",
    "snow_vertical": "TRUE",
    "deli_oven_market_density": "MEDIUM",
    "handyman_license_status": "Y_HIC_REGISTRATION",
    "handyman_threshold_usd": "ANY_1_4_FAMILY_WORK",
    "handyman_city_county_override_notes": "",
    "pest_control_license_required": "Y",
    "pest_control_agency": "MA Dept of Agricultural Resources",
    "biohazard_license_required_notes": "N",
    "restoration_threshold_usd": "0",
    "mold_remediation_specific_license_notes": "N",
    "confidence": "HIGH"
  },
  {
    "state": "Virginia",
    "abbreviation": "VA",
    "tier": "2",
    "priority_rank": "14",
    "snow_vertical": "TRUE",
    "deli_oven_market_density": "LOW",
    "handyman_license_status": "Y_CLASS_A_B_C",
    "handyman_threshold_usd": "1000 (Class C <=10000)",
    "handyman_city_county_override_notes": "",
    "pest_control_license_required": "Y",
    "pest_control_agency": "VA Dept of Agriculture & Consumer Services",
    "biohazard_license_required_notes": "N",
    "restoration_threshold_usd": "1000",
    "mold_remediation_specific_license_notes": "IICRC certification required to remediate residential mold (HB 1270, VCPA, eff 7/1/2024)",
    "confidence": "HIGH"
  },
  {
    "state": "Washington",
    "abbreviation": "WA",
    "tier": "2",
    "priority_rank": "15",
    "snow_vertical": "TRUE",
    "deli_oven_market_density": "LOW",
    "handyman_license_status": "Y_L_AND_I_REGISTRATION",
    "handyman_threshold_usd": "ALL_CONSTRUCTION_WORK",
    "handyman_city_county_override_notes": "",
    "pest_control_license_required": "Y",
    "pest_control_agency": "WA State Dept of Agriculture",
    "biohazard_license_required_notes": "N",
    "restoration_threshold_usd": "0",
    "mold_remediation_specific_license_notes": "N",
    "confidence": "HIGH"
  },
  {
    "state": "Michigan",
    "abbreviation": "MI",
    "tier": "2",
    "priority_rank": "16",
    "snow_vertical": "TRUE",
    "deli_oven_market_density": "LOW",
    "handyman_license_status": "Y_RESIDENTIAL_BUILDER",
    "handyman_threshold_usd": "REPAIR_ALTERATION_WORK",
    "handyman_city_county_override_notes": "",
    "pest_control_license_required": "Y",
    "pest_control_agency": "MI Dept of Agriculture & Rural Development",
    "biohazard_license_required_notes": "N",
    "restoration_threshold_usd": "0",
    "mold_remediation_specific_license_notes": "N",
    "confidence": "MEDIUM"
  },
  {
    "state": "Maryland",
    "abbreviation": "MD",
    "tier": "2",
    "priority_rank": "17",
    "snow_vertical": "TRUE",
    "deli_oven_market_density": "MEDIUM",
    "handyman_license_status": "Y_MHIC_LICENSE",
    "handyman_threshold_usd": "ANY_HOME_IMPROVEMENT",
    "handyman_city_county_override_notes": "",
    "pest_control_license_required": "Y",
    "pest_control_agency": "MD Dept of Agriculture",
    "biohazard_license_required_notes": "N",
    "restoration_threshold_usd": "0",
    "mold_remediation_specific_license_notes": "POSSIBLY_UNDER_MHIC_VERIFY",
    "confidence": "HIGH"
  },
  {
    "state": "Colorado",
    "abbreviation": "CO",
    "tier": "2",
    "priority_rank": "18",
    "snow_vertical": "TRUE",
    "deli_oven_market_density": "LOW",
    "handyman_license_status": "LOCAL_ONLY",
    "handyman_threshold_usd": "SET_LOCALLY",
    "handyman_city_county_override_notes": "Denver, Colorado Springs, Boulder license",
    "pest_control_license_required": "Y",
    "pest_control_agency": "CO Dept of Agriculture",
    "biohazard_license_required_notes": "N",
    "restoration_threshold_usd": "LOCAL",
    "mold_remediation_specific_license_notes": "N",
    "confidence": "HIGH"
  },
  {
    "state": "Tennessee",
    "abbreviation": "TN",
    "tier": "2",
    "priority_rank": "19",
    "snow_vertical": "FALSE",
    "deli_oven_market_density": "LOW",
    "handyman_license_status": "Y_GC",
    "handyman_threshold_usd": ">25000 GC; 3000-24999 Home Improvement (9 counties)",
    "handyman_city_county_override_notes": "Home Improvement license only in Bradley/Davidson/Hamilton/Haywood/Knox/Marion/Robertson/Rutherford/Shelby",
    "pest_control_license_required": "Y",
    "pest_control_agency": "TN Dept of Agriculture",
    "biohazard_license_required_notes": "N",
    "restoration_threshold_usd": "25000",
    "mold_remediation_specific_license_notes": "Remediator - mold classification on contractor license",
    "confidence": "HIGH"
  },
  {
    "state": "Indiana",
    "abbreviation": "IN",
    "tier": "3",
    "priority_rank": "20",
    "snow_vertical": "TRUE",
    "deli_oven_market_density": "LOW",
    "handyman_license_status": "LOCAL_ONLY",
    "handyman_threshold_usd": "SET_LOCALLY",
    "handyman_city_county_override_notes": "Most large cities require registration",
    "pest_control_license_required": "Y",
    "pest_control_agency": "Office of Indiana State Chemist (Purdue)",
    "biohazard_license_required_notes": "N",
    "restoration_threshold_usd": "LOCAL",
    "mold_remediation_specific_license_notes": "N",
    "confidence": "MEDIUM"
  },
  {
    "state": "Missouri",
    "abbreviation": "MO",
    "tier": "3",
    "priority_rank": "21",
    "snow_vertical": "TRUE",
    "deli_oven_market_density": "LOW",
    "handyman_license_status": "LOCAL_ONLY",
    "handyman_threshold_usd": "SET_LOCALLY",
    "handyman_city_county_override_notes": "Kansas City, St. Louis differ",
    "pest_control_license_required": "Y",
    "pest_control_agency": "MO Dept of Agriculture",
    "biohazard_license_required_notes": "N",
    "restoration_threshold_usd": "LOCAL",
    "mold_remediation_specific_license_notes": "N",
    "confidence": "MEDIUM"
  },
  {
    "state": "Wisconsin",
    "abbreviation": "WI",
    "tier": "3",
    "priority_rank": "22",
    "snow_vertical": "TRUE",
    "deli_oven_market_density": "LOW",
    "handyman_license_status": "Y_DWELLING_CONTRACTOR",
    "handyman_threshold_usd": "Permit work / >1000",
    "handyman_city_county_override_notes": "",
    "pest_control_license_required": "Y",
    "pest_control_agency": "WI Dept of Agriculture, Trade & Consumer Protection",
    "biohazard_license_required_notes": "N",
    "restoration_threshold_usd": "1000",
    "mold_remediation_specific_license_notes": "N",
    "confidence": "MEDIUM"
  },
  {
    "state": "Minnesota",
    "abbreviation": "MN",
    "tier": "3",
    "priority_rank": "23",
    "snow_vertical": "TRUE",
    "deli_oven_market_density": "LOW",
    "handyman_license_status": "Y_RESIDENTIAL_REMODELER",
    "handyman_threshold_usd": ">15000/yr",
    "handyman_city_county_override_notes": "",
    "pest_control_license_required": "Y",
    "pest_control_agency": "MN Dept of Agriculture",
    "biohazard_license_required_notes": "N",
    "restoration_threshold_usd": "15000",
    "mold_remediation_specific_license_notes": "N",
    "confidence": "MEDIUM"
  },
  {
    "state": "South Carolina",
    "abbreviation": "SC",
    "tier": "3",
    "priority_rank": "24",
    "snow_vertical": "FALSE",
    "deli_oven_market_density": "LOW",
    "handyman_license_status": "DEPENDS",
    "handyman_threshold_usd": "Specialty >500; GC >10000",
    "handyman_city_county_override_notes": "",
    "pest_control_license_required": "Y",
    "pest_control_agency": "Clemson University Dept of Pesticide Regulation",
    "biohazard_license_required_notes": "N",
    "restoration_threshold_usd": "10000",
    "mold_remediation_specific_license_notes": "N",
    "confidence": "MEDIUM"
  },
  {
    "state": "Alabama",
    "abbreviation": "AL",
    "tier": "3",
    "priority_rank": "25",
    "snow_vertical": "FALSE",
    "deli_oven_market_density": "LOW",
    "handyman_license_status": "N_GC_ONLY",
    "handyman_threshold_usd": "10000 res / 50000 comm (verify comm figure)",
    "handyman_city_county_override_notes": "",
    "pest_control_license_required": "Y",
    "pest_control_agency": "AL Dept of Agriculture & Industries",
    "biohazard_license_required_notes": "N",
    "restoration_threshold_usd": "10000",
    "mold_remediation_specific_license_notes": "N",
    "confidence": "LOW"
  },
  {
    "state": "Louisiana",
    "abbreviation": "LA",
    "tier": "3",
    "priority_rank": "26",
    "snow_vertical": "FALSE",
    "deli_oven_market_density": "LOW",
    "handyman_license_status": "DEPENDS",
    "handyman_threshold_usd": "<7500 none; 7500-75000 HIR; >75000 res / >50000 comm",
    "handyman_city_county_override_notes": "New Orleans parish permits",
    "pest_control_license_required": "Y",
    "pest_control_agency": "LA Dept of Agriculture & Forestry",
    "biohazard_license_required_notes": "N",
    "restoration_threshold_usd": "75000",
    "mold_remediation_specific_license_notes": "Y - mold remediation specialist (State Licensing Board for Contractors)",
    "confidence": "HIGH"
  },
  {
    "state": "Kentucky",
    "abbreviation": "KY",
    "tier": "3",
    "priority_rank": "27",
    "snow_vertical": "TRUE",
    "deli_oven_market_density": "LOW",
    "handyman_license_status": "LOCAL_ONLY",
    "handyman_threshold_usd": "SET_LOCALLY",
    "handyman_city_county_override_notes": "Louisville & Lexington registration",
    "pest_control_license_required": "Y",
    "pest_control_agency": "KY Dept of Agriculture",
    "biohazard_license_required_notes": "N",
    "restoration_threshold_usd": "LOCAL",
    "mold_remediation_specific_license_notes": "STATUTORY_STANDARD_NO_LICENSE",
    "confidence": "MEDIUM"
  },
  {
    "state": "Oregon",
    "abbreviation": "OR",
    "tier": "3",
    "priority_rank": "28",
    "snow_vertical": "TRUE",
    "deli_oven_market_density": "LOW",
    "handyman_license_status": "Y_CCB_LICENSE",
    "handyman_threshold_usd": "Nearly all work; 1000 minor exemption",
    "handyman_city_county_override_notes": "",
    "pest_control_license_required": "Y",
    "pest_control_agency": "OR Dept of Agriculture",
    "biohazard_license_required_notes": "N",
    "restoration_threshold_usd": "1000",
    "mold_remediation_specific_license_notes": "Remediator - restoration endorsement on CCB license",
    "confidence": "HIGH"
  },
  {
    "state": "Connecticut",
    "abbreviation": "CT",
    "tier": "3",
    "priority_rank": "29",
    "snow_vertical": "TRUE",
    "deli_oven_market_density": "LOW",
    "handyman_license_status": "Y_HIC_REGISTRATION",
    "handyman_threshold_usd": "ANY_RESIDENTIAL_WORK",
    "handyman_city_county_override_notes": "",
    "pest_control_license_required": "Y",
    "pest_control_agency": "CT Dept of Energy & Environmental Protection (DEEP)",
    "biohazard_license_required_notes": "N",
    "restoration_threshold_usd": "0",
    "mold_remediation_specific_license_notes": "STATUTORY_STANDARD_NO_LICENSE",
    "confidence": "HIGH"
  },
  {
    "state": "Utah",
    "abbreviation": "UT",
    "tier": "4",
    "priority_rank": "30",
    "snow_vertical": "TRUE",
    "deli_oven_market_density": "LOW",
    "handyman_license_status": "Y_DOPL",
    "handyman_threshold_usd": "3000 (1000-3000 exemption filing)",
    "handyman_city_county_override_notes": "",
    "pest_control_license_required": "Y",
    "pest_control_agency": "UT Dept of Agriculture & Food",
    "biohazard_license_required_notes": "N",
    "restoration_threshold_usd": "3000",
    "mold_remediation_specific_license_notes": "N",
    "confidence": "MEDIUM"
  },
  {
    "state": "Nevada",
    "abbreviation": "NV",
    "tier": "4",
    "priority_rank": "31",
    "snow_vertical": "FALSE",
    "deli_oven_market_density": "LOW",
    "handyman_license_status": "Y",
    "handyman_threshold_usd": "1000",
    "handyman_city_county_override_notes": "",
    "pest_control_license_required": "Y",
    "pest_control_agency": "NV Dept of Agriculture",
    "biohazard_license_required_notes": "N",
    "restoration_threshold_usd": "1000",
    "mold_remediation_specific_license_notes": "N",
    "confidence": "MEDIUM"
  },
  {
    "state": "Arkansas",
    "abbreviation": "AR",
    "tier": "4",
    "priority_rank": "32",
    "snow_vertical": "FALSE",
    "deli_oven_market_density": "LOW",
    "handyman_license_status": "DEPENDS",
    "handyman_threshold_usd": "2000 (Remodeler 2000-50000)",
    "handyman_city_county_override_notes": "City business licenses",
    "pest_control_license_required": "Y",
    "pest_control_agency": "AR Dept of Agriculture, State Plant Board",
    "biohazard_license_required_notes": "N",
    "restoration_threshold_usd": "2000",
    "mold_remediation_specific_license_notes": "N",
    "confidence": "MEDIUM"
  },
  {
    "state": "Oklahoma",
    "abbreviation": "OK",
    "tier": "4",
    "priority_rank": "33",
    "snow_vertical": "FALSE",
    "deli_oven_market_density": "LOW",
    "handyman_license_status": "N",
    "handyman_threshold_usd": "No state GC license",
    "handyman_city_county_override_notes": "Cities may require registration",
    "pest_control_license_required": "Y",
    "pest_control_agency": "OK Dept of Agriculture, Food & Forestry",
    "biohazard_license_required_notes": "N",
    "restoration_threshold_usd": "0",
    "mold_remediation_specific_license_notes": "N",
    "confidence": "MEDIUM"
  },
  {
    "state": "Iowa",
    "abbreviation": "IA",
    "tier": "4",
    "priority_rank": "34",
    "snow_vertical": "TRUE",
    "deli_oven_market_density": "LOW",
    "handyman_license_status": "REGISTRATION",
    "handyman_threshold_usd": ">=2000/yr",
    "handyman_city_county_override_notes": "Des Moines adds licenses",
    "pest_control_license_required": "Y",
    "pest_control_agency": "IA Dept of Agriculture & Land Stewardship",
    "biohazard_license_required_notes": "N",
    "restoration_threshold_usd": "2000",
    "mold_remediation_specific_license_notes": "N",
    "confidence": "MEDIUM"
  },
  {
    "state": "Kansas",
    "abbreviation": "KS",
    "tier": "4",
    "priority_rank": "35",
    "snow_vertical": "TRUE",
    "deli_oven_market_density": "LOW",
    "handyman_license_status": "LOCAL_ONLY",
    "handyman_threshold_usd": "SET_LOCALLY (<1000 typical)",
    "handyman_city_county_override_notes": "Johnson County Class C license",
    "pest_control_license_required": "Y",
    "pest_control_agency": "KS Dept of Agriculture",
    "biohazard_license_required_notes": "N",
    "restoration_threshold_usd": "LOCAL",
    "mold_remediation_specific_license_notes": "N",
    "confidence": "MEDIUM"
  },
  {
    "state": "New Mexico",
    "abbreviation": "NM",
    "tier": "4",
    "priority_rank": "36",
    "snow_vertical": "TRUE",
    "deli_oven_market_density": "LOW",
    "handyman_license_status": "Y",
    "handyman_threshold_usd": "Any construction",
    "handyman_city_county_override_notes": "",
    "pest_control_license_required": "Y",
    "pest_control_agency": "NM Dept of Agriculture",
    "biohazard_license_required_notes": "N",
    "restoration_threshold_usd": "0",
    "mold_remediation_specific_license_notes": "N",
    "confidence": "MEDIUM"
  },
  {
    "state": "Nebraska",
    "abbreviation": "NE",
    "tier": "5",
    "priority_rank": "37",
    "snow_vertical": "TRUE",
    "deli_oven_market_density": "LOW",
    "handyman_license_status": "N_REGISTER",
    "handyman_threshold_usd": "Register w/ Dept of Labor",
    "handyman_city_county_override_notes": "",
    "pest_control_license_required": "Y",
    "pest_control_agency": "NE Dept of Agriculture",
    "biohazard_license_required_notes": "N",
    "restoration_threshold_usd": "0",
    "mold_remediation_specific_license_notes": "N",
    "confidence": "MEDIUM"
  },
  {
    "state": "West Virginia",
    "abbreviation": "WV",
    "tier": "5",
    "priority_rank": "38",
    "snow_vertical": "TRUE",
    "deli_oven_market_density": "LOW",
    "handyman_license_status": "Y_CONTRACTOR_LICENSE",
    "handyman_threshold_usd": "2500",
    "handyman_city_county_override_notes": "",
    "pest_control_license_required": "Y",
    "pest_control_agency": "WV Dept of Agriculture",
    "biohazard_license_required_notes": "N",
    "restoration_threshold_usd": "2500",
    "mold_remediation_specific_license_notes": "N",
    "confidence": "MEDIUM"
  },
  {
    "state": "Idaho",
    "abbreviation": "ID",
    "tier": "5",
    "priority_rank": "39",
    "snow_vertical": "TRUE",
    "deli_oven_market_density": "LOW",
    "handyman_license_status": "REGISTRATION",
    "handyman_threshold_usd": ">2000/yr",
    "handyman_city_county_override_notes": "Boise adds requirements",
    "pest_control_license_required": "Y",
    "pest_control_agency": "Idaho State Dept of Agriculture",
    "biohazard_license_required_notes": "N",
    "restoration_threshold_usd": "2000",
    "mold_remediation_specific_license_notes": "N",
    "confidence": "MEDIUM"
  },
  {
    "state": "New Hampshire",
    "abbreviation": "NH",
    "tier": "5",
    "priority_rank": "40",
    "snow_vertical": "TRUE",
    "deli_oven_market_density": "LOW",
    "handyman_license_status": "N",
    "handyman_threshold_usd": "No state license",
    "handyman_city_county_override_notes": "",
    "pest_control_license_required": "Y",
    "pest_control_agency": "NH Dept of Agriculture, Div of Pesticide Control",
    "biohazard_license_required_notes": "N",
    "restoration_threshold_usd": "0",
    "mold_remediation_specific_license_notes": "Assessor only (RSA 310-A)",
    "confidence": "MEDIUM"
  },
  {
    "state": "Maine",
    "abbreviation": "ME",
    "tier": "5",
    "priority_rank": "41",
    "snow_vertical": "TRUE",
    "deli_oven_market_density": "LOW",
    "handyman_license_status": "LOCAL_ONLY",
    "handyman_threshold_usd": "No state limit; >3000 written contract required",
    "handyman_city_county_override_notes": "Portland building-contractor license",
    "pest_control_license_required": "Y",
    "pest_control_agency": "ME Dept of Agriculture, Board of Pesticides Control",
    "biohazard_license_required_notes": "N",
    "restoration_threshold_usd": "LOCAL",
    "mold_remediation_specific_license_notes": "STATUTORY_STANDARD_NO_LICENSE",
    "confidence": "MEDIUM"
  },
  {
    "state": "Rhode Island",
    "abbreviation": "RI",
    "tier": "5",
    "priority_rank": "42",
    "snow_vertical": "TRUE",
    "deli_oven_market_density": "LOW",
    "handyman_license_status": "N_REGISTRATION",
    "handyman_threshold_usd": "Register w/ CRLB (minor repairs <500 exempt)",
    "handyman_city_county_override_notes": "",
    "pest_control_license_required": "Y",
    "pest_control_agency": "RI Dept of Environmental Management",
    "biohazard_license_required_notes": "N",
    "restoration_threshold_usd": "500",
    "mold_remediation_specific_license_notes": "N",
    "confidence": "MEDIUM"
  },
  {
    "state": "Montana",
    "abbreviation": "MT",
    "tier": "5",
    "priority_rank": "43",
    "snow_vertical": "TRUE",
    "deli_oven_market_density": "LOW",
    "handyman_license_status": "N_REGISTER_IF_EMPLOYEES",
    "handyman_threshold_usd": "Register w/ Dept of Labor",
    "handyman_city_county_override_notes": "Local rules vary",
    "pest_control_license_required": "Y",
    "pest_control_agency": "MT Dept of Agriculture",
    "biohazard_license_required_notes": "N",
    "restoration_threshold_usd": "0",
    "mold_remediation_specific_license_notes": "N",
    "confidence": "MEDIUM"
  },
  {
    "state": "Delaware",
    "abbreviation": "DE",
    "tier": "5",
    "priority_rank": "44",
    "snow_vertical": "TRUE",
    "deli_oven_market_density": "LOW",
    "handyman_license_status": "REVENUE_BASED",
    "handyman_threshold_usd": "50000/yr receipts",
    "handyman_city_county_override_notes": "New Castle County stricter",
    "pest_control_license_required": "Y",
    "pest_control_agency": "DE Dept of Agriculture",
    "biohazard_license_required_notes": "N",
    "restoration_threshold_usd": "50000",
    "mold_remediation_specific_license_notes": "N",
    "confidence": "MEDIUM"
  },
  {
    "state": "South Dakota",
    "abbreviation": "SD",
    "tier": "5",
    "priority_rank": "45",
    "snow_vertical": "TRUE",
    "deli_oven_market_density": "LOW",
    "handyman_license_status": "N",
    "handyman_threshold_usd": "No state license",
    "handyman_city_county_override_notes": "",
    "pest_control_license_required": "Y",
    "pest_control_agency": "SD Dept of Agriculture & Natural Resources",
    "biohazard_license_required_notes": "N",
    "restoration_threshold_usd": "0",
    "mold_remediation_specific_license_notes": "N",
    "confidence": "MEDIUM"
  },
  {
    "state": "North Dakota",
    "abbreviation": "ND",
    "tier": "5",
    "priority_rank": "46",
    "snow_vertical": "TRUE",
    "deli_oven_market_density": "LOW",
    "handyman_license_status": "Y",
    "handyman_threshold_usd": "4000",
    "handyman_city_county_override_notes": "",
    "pest_control_license_required": "Y",
    "pest_control_agency": "ND Dept of Agriculture",
    "biohazard_license_required_notes": "N",
    "restoration_threshold_usd": "4000",
    "mold_remediation_specific_license_notes": "N",
    "confidence": "MEDIUM"
  },
  {
    "state": "Hawaii",
    "abbreviation": "HI",
    "tier": "5",
    "priority_rank": "47",
    "snow_vertical": "FALSE",
    "deli_oven_market_density": "LOW",
    "handyman_license_status": "Y",
    "handyman_threshold_usd": "1000 (or 2+ trades)",
    "handyman_city_county_override_notes": "County permits enforced",
    "pest_control_license_required": "Y",
    "pest_control_agency": "HI Dept of Agriculture",
    "biohazard_license_required_notes": "N",
    "restoration_threshold_usd": "1000",
    "mold_remediation_specific_license_notes": "N",
    "confidence": "MEDIUM"
  },
  {
    "state": "Alaska",
    "abbreviation": "AK",
    "tier": "5",
    "priority_rank": "48",
    "snow_vertical": "TRUE",
    "deli_oven_market_density": "LOW",
    "handyman_license_status": "Y",
    "handyman_threshold_usd": "10000",
    "handyman_city_county_override_notes": "Boroughs may add tax registration",
    "pest_control_license_required": "Y",
    "pest_control_agency": "AK Dept of Environmental Conservation",
    "biohazard_license_required_notes": "N",
    "restoration_threshold_usd": "10000",
    "mold_remediation_specific_license_notes": "N",
    "confidence": "MEDIUM"
  },
  {
    "state": "Vermont",
    "abbreviation": "VT",
    "tier": "5",
    "priority_rank": "49",
    "snow_vertical": "TRUE",
    "deli_oven_market_density": "LOW",
    "handyman_license_status": "LOCAL_ONLY",
    "handyman_threshold_usd": "No state GC license",
    "handyman_city_county_override_notes": "Municipal; trades via Div of Fire Safety",
    "pest_control_license_required": "Y",
    "pest_control_agency": "VT Agency of Agriculture, Food & Markets",
    "biohazard_license_required_notes": "N",
    "restoration_threshold_usd": "LOCAL",
    "mold_remediation_specific_license_notes": "N",
    "confidence": "MEDIUM"
  },
  {
    "state": "Wyoming",
    "abbreviation": "WY",
    "tier": "5",
    "priority_rank": "50",
    "snow_vertical": "TRUE",
    "deli_oven_market_density": "LOW",
    "handyman_license_status": "LOCAL_ONLY",
    "handyman_threshold_usd": "No state license",
    "handyman_city_county_override_notes": "Larger cities license",
    "pest_control_license_required": "Y",
    "pest_control_agency": "WY Dept of Agriculture",
    "biohazard_license_required_notes": "N",
    "restoration_threshold_usd": "LOCAL",
    "mold_remediation_specific_license_notes": "N",
    "confidence": "MEDIUM"
  },
  {
    "state": "Mississippi",
    "abbreviation": "MS",
    "tier": "5",
    "priority_rank": "51",
    "snow_vertical": "FALSE",
    "deli_oven_market_density": "LOW",
    "handyman_license_status": "Y_GC",
    "handyman_threshold_usd": "Res remodel >10000; build >50000",
    "handyman_city_county_override_notes": "",
    "pest_control_license_required": "Y",
    "pest_control_agency": "MS Dept of Agriculture & Commerce",
    "biohazard_license_required_notes": "N",
    "restoration_threshold_usd": "10000",
    "mold_remediation_specific_license_notes": "N",
    "confidence": "MEDIUM"
  }
];

const SOURCE =
  "Anthropic Advanced Research pass, Aug 26 2026 - review by licensing attorney before operational use";

const nz = (v: string | undefined) => (v && v.trim() !== "" ? v.trim() : null);

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok");
  const supabase = createClient(
    Deno.env.get("SUPABASE_URL")!,
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
  );

  const updated: string[] = [];
  const failures: { state: string; error: string }[] = [];

  for (const r of ROWS) {
    const patch = {
      abbreviation: r.abbreviation,
      tier: r.tier,
      priority_rank: Number(r.priority_rank),
      snow_vertical: r.snow_vertical === "TRUE",
      deli_oven_market_density: nz(r.deli_oven_market_density),
      handyman_license_status: nz(r.handyman_license_status),
      handyman_threshold_usd: nz(r.handyman_threshold_usd),
      handyman_city_county_override_notes: nz(r.handyman_city_county_override_notes),
      pest_control_license_required: r.pest_control_license_required === "Y",
      pest_control_agency: nz(r.pest_control_agency),
      biohazard_license_required_notes: nz(r.biohazard_license_required_notes),
      restoration_threshold_usd: nz(r.restoration_threshold_usd),
      mold_remediation_specific_license_notes: nz(r.mold_remediation_specific_license_notes),
      confidence: r.confidence,
      verified: true,
      last_verified_date: "2026-08-26",
      source: SOURCE,
    };

    try {
      await verifiedUpdate(`load state config ${r.abbreviation}`, () =>
        supabase
          .from("icw_state_config")
          .update(patch)
          .eq("state", r.abbreviation)
      );
      updated.push(r.abbreviation);
    } catch (e) {
      failures.push({ state: r.abbreviation, error: (e as Error).message });
    }
  }

  const { count: total } = await supabase
    .from("icw_state_config")
    .select("id", { count: "exact", head: true });
  const { count: verifiedCount } = await supabase
    .from("icw_state_config")
    .select("id", { count: "exact", head: true })
    .eq("verified", true);
  const { count: pending } = await supabase
    .from("icw_state_config")
    .select("id", { count: "exact", head: true })
    .eq("confidence", "PENDING_VERIFICATION");

  return new Response(
    JSON.stringify({
      updated: updated.length,
      failures,
      totals: { total, verified: verifiedCount, pending_verification: pending },
    }),
    { headers: { "Content-Type": "application/json" } },
  );
});
