import { useState, useEffect } from 'react';
import { useVASession } from '@/contexts/VASessionContext';
import { useAuth } from '@/contexts/AuthContext';
import { supabase } from '@/integrations/supabase/client';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Plus, Trash2, Loader2, CreditCard, SplitSquareHorizontal, Package } from 'lucide-react';
import { toast } from 'sonner';

// Parse a package price string like "$1,500", "$2,997", "$5,000+" → number.
// Returns 0 for non-numeric ("Custom") so the VA can fill it in manually.
function parsePackagePrice(raw: string | null | undefined): number {
  if (!raw) return 0;
  const cleaned = String(raw).replace(/[^0-9.]/g, '');
  const n = parseFloat(cleaned);
  return Number.isFinite(n) ? n : 0;
}

interface LineItem { description: string; price: number; }

interface VAInvoiceModalProps {
  open: boolean;
  onClose: () => void;
  lead?: { id: string; business_name: string; phone?: string; email?: string } | null;
  sendOnSave?: boolean;
}

const SERVICE_TYPES = [
  'Website Design', 'SEO Package', 'Google Ads Management',
  'Social Media Marketing', 'Full Digital Package', 'Consultation', 'Other',
];

type PaymentType = 'full' | 'split';

export function VAInvoiceModal({ open, onClose, lead, sendOnSave }: VAInvoiceModalProps) {
  const { t } = useVASession();
  const { user } = useAuth();
  const qc = useQueryClient();
  const [saving, setSaving] = useState(false);
  const [form, setForm] = useState({
    customerName: '',
    customerEmail: '',
    serviceType: '',
    dueDate: '',
    notes: '',
    paymentType: 'split' as PaymentType,
    depositPercent: 50,
    lineItems: [{ description: '', price: 0 }] as LineItem[],
  });

  useEffect(() => {
    if (open && lead) {
      setForm(f => ({
        ...f,
        customerName: lead.business_name || '',
        customerEmail: lead.email || f.customerEmail,
      }));
    }
  }, [open, lead]);

  const total = form.lineItems.reduce((s, i) => s + (i.price || 0), 0);
  const deposit = +(total * (form.depositPercent / 100)).toFixed(2);
  const finalAmt = +(total - deposit).toFixed(2);

  const addItem = () => setForm(f => ({ ...f, lineItems: [...f.lineItems, { description: '', price: 0 }] }));
  const removeItem = (idx: number) => setForm(f => ({ ...f, lineItems: f.lineItems.filter((_, i) => i !== idx) }));
  const updateItem = (idx: number, field: keyof LineItem, value: string | number) => {
    setForm(f => ({
      ...f,
      lineItems: f.lineItems.map((item, i) => i === idx ? { ...item, [field]: value } : item),
    }));
  };

  const handleSave = async () => {
    if (!form.customerName || form.lineItems.length === 0 || total <= 0) {
      toast.error('Customer name + at least one line item with a price are required.');
      return;
    }
    setSaving(true);
    try {
      // 1. Persist invoice (draft) — pay link is generated by the edge function next.
      const { data: inserted, error } = await (supabase as any)
        .from('va_invoices')
        .insert({
          lead_id: lead?.id || null,
          va_id: user?.id,
          customer_name: form.customerName,
          customer_email: form.customerEmail || null,
          service_type: form.serviceType || null,
          line_items: form.lineItems,
          total,
          status: 'draft',
          payment_type: form.paymentType,
          deposit_percent: form.paymentType === 'split' ? form.depositPercent : 100,
          due_date: form.dueDate || null,
          notes: form.notes || null,
        })
        .select('id')
        .single();
      if (error) throw error;
      const invoiceId = inserted?.id;

      // 2. Create Stripe Checkout sessions (full or 50/50 split).
      const { data: stripeData, error: stripeErr } = await supabase.functions.invoke(
        'va-stripe-checkout',
        { body: { invoice_id: invoiceId } },
      );
      if (stripeErr || (stripeData as any)?.error) {
        throw new Error(stripeErr?.message || (stripeData as any)?.error || 'Stripe checkout failed');
      }

      qc.invalidateQueries({ queryKey: ['va-invoices', user?.id] });

      // 3. Optionally email the invoice (already includes the new payment links).
      if (sendOnSave && invoiceId) {
        try {
          const { data: sendData, error: sendErr } = await supabase.functions.invoke('va-send-invoice', {
            body: { invoice_id: invoiceId, channel: 'email' },
          });
          if (sendErr || (sendData as any)?.error) {
            throw new Error(sendErr?.message || (sendData as any)?.error);
          }
          toast.success(`Invoice sent to ${(sendData as any)?.sent_to || 'customer'}`);
          qc.invalidateQueries({ queryKey: ['va-invoices', user?.id] });
        } catch (e: any) {
          toast.warning(`Invoice + Stripe link saved — email failed: ${e.message}`);
        }
      } else {
        toast.success(
          form.paymentType === 'split'
            ? `Invoice saved · Stripe deposit + final links ready`
            : `Invoice saved · Stripe payment link ready`,
        );
      }
      onClose();
    } catch (err: any) {
      toast.error(err.message || 'Failed to save invoice');
    } finally {
      setSaving(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={onClose}>
      <DialogContent className="max-w-lg bg-slate-900 border-cyan-500/20 text-white max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>{sendOnSave ? 'Create & Send Invoice' : t('va.invoice.title')}</DialogTitle>
        </DialogHeader>
        <div className="space-y-4">
          <div className="grid grid-cols-2 gap-3">
            <div>
              <label className="text-xs text-slate-400">{t('va.invoice.customerName')}</label>
              <Input value={form.customerName} onChange={e => setForm(f => ({ ...f, customerName: e.target.value }))}
                className="bg-slate-800 border-slate-700 text-white" />
            </div>
            <div>
              <label className="text-xs text-slate-400">Customer Email</label>
              <Input type="email" value={form.customerEmail} onChange={e => setForm(f => ({ ...f, customerEmail: e.target.value }))}
                placeholder="customer@example.com" className="bg-slate-800 border-slate-700 text-white" />
            </div>
          </div>

          <div>
            <label className="text-xs text-slate-400">{t('va.invoice.serviceType')}</label>
            <Select value={form.serviceType} onValueChange={v => setForm(f => ({ ...f, serviceType: v }))}>
              <SelectTrigger className="bg-slate-800 border-slate-700 text-white"><SelectValue /></SelectTrigger>
              <SelectContent>
                {SERVICE_TYPES.map(s => <SelectItem key={s} value={s}>{s}</SelectItem>)}
              </SelectContent>
            </Select>
          </div>

          <div>
            <label className="text-xs text-slate-400 mb-2 block">{t('va.invoice.lineItems')}</label>
            {form.lineItems.map((item, i) => (
              <div key={i} className="flex gap-2 mb-2">
                <Input value={item.description} onChange={e => updateItem(i, 'description', e.target.value)}
                  placeholder={t('va.invoice.description')} className="flex-1 bg-slate-800 border-slate-700 text-white text-sm" />
                <Input type="number" value={item.price || ''} onChange={e => updateItem(i, 'price', parseFloat(e.target.value) || 0)}
                  placeholder="$0" className="w-24 bg-slate-800 border-slate-700 text-white text-sm" />
                {form.lineItems.length > 1 && (
                  <Button size="icon" variant="ghost" className="text-red-400 h-9 w-9" onClick={() => removeItem(i)}>
                    <Trash2 className="h-3 w-3" />
                  </Button>
                )}
              </div>
            ))}
            <Button size="sm" variant="outline" onClick={addItem} className="text-xs border-slate-700">
              <Plus className="h-3 w-3 mr-1" /> {t('va.invoice.addItem')}
            </Button>
          </div>

          {/* Payment type chooser */}
          <div>
            <label className="text-xs text-slate-400 mb-2 block">Payment Plan</label>
            <div className="grid grid-cols-2 gap-2">
              <button
                type="button"
                onClick={() => setForm(f => ({ ...f, paymentType: 'full' }))}
                className={`p-3 rounded-lg border text-left transition-all ${
                  form.paymentType === 'full'
                    ? 'border-cyan-500 bg-cyan-500/10'
                    : 'border-slate-700 hover:border-slate-500'
                }`}
              >
                <div className="flex items-center gap-2 text-sm font-medium">
                  <CreditCard className="h-4 w-4" /> Pay in Full
                </div>
                <div className="text-[11px] text-slate-400 mt-1">Single payment link.</div>
              </button>
              <button
                type="button"
                onClick={() => setForm(f => ({ ...f, paymentType: 'split' }))}
                className={`p-3 rounded-lg border text-left transition-all ${
                  form.paymentType === 'split'
                    ? 'border-cyan-500 bg-cyan-500/10'
                    : 'border-slate-700 hover:border-slate-500'
                }`}
              >
                <div className="flex items-center gap-2 text-sm font-medium">
                  <SplitSquareHorizontal className="h-4 w-4" /> 50% Now / 50% on Completion
                </div>
                <div className="text-[11px] text-slate-400 mt-1">Two Stripe links: deposit + final.</div>
              </button>
            </div>
          </div>

          <div className="bg-slate-800 rounded-lg p-3 space-y-1.5 text-sm">
            <div className="flex justify-between">
              <span className="text-slate-400">Total</span>
              <span className="font-bold text-cyan-400 text-lg">${total.toFixed(2)}</span>
            </div>
            {form.paymentType === 'split' && (
              <>
                <div className="flex justify-between text-xs text-slate-300">
                  <span>Deposit (now)</span>
                  <span className="font-mono">${deposit.toFixed(2)}</span>
                </div>
                <div className="flex justify-between text-xs text-slate-300">
                  <span>Final (on completion)</span>
                  <span className="font-mono">${finalAmt.toFixed(2)}</span>
                </div>
              </>
            )}
          </div>

          <div className="grid grid-cols-2 gap-3">
            <div>
              <label className="text-xs text-slate-400">{t('va.invoice.dueDate')}</label>
              <Input type="date" value={form.dueDate} onChange={e => setForm(f => ({ ...f, dueDate: e.target.value }))}
                className="bg-slate-800 border-slate-700 text-white" />
            </div>
            <div>
              <label className="text-xs text-slate-400">{t('va.invoice.notes')}</label>
              <Input value={form.notes} onChange={e => setForm(f => ({ ...f, notes: e.target.value }))}
                className="bg-slate-800 border-slate-700 text-white" />
            </div>
          </div>

          <Button onClick={handleSave} disabled={saving || total <= 0} className="w-full bg-cyan-600 hover:bg-cyan-700">
            {saving ? <Loader2 className="h-4 w-4 animate-spin mr-2" /> : <CreditCard className="h-4 w-4 mr-2" />}
            {sendOnSave ? 'Save, Generate Stripe Link & Send' : 'Save & Generate Stripe Link'}
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}
