-- Add new columns to businesses table for Business Profile Builder
ALTER TABLE public.businesses
ADD COLUMN IF NOT EXISTS tagline text,
ADD COLUMN IF NOT EXISTS short_description text,
ADD COLUMN IF NOT EXISTS long_description text,
ADD COLUMN IF NOT EXISTS category text,
ADD COLUMN IF NOT EXISTS brand_type text,
ADD COLUMN IF NOT EXISTS brand_banner_url text,
ADD COLUMN IF NOT EXISTS secondary_color text,
ADD COLUMN IF NOT EXISTS accent_color text,
ADD COLUMN IF NOT EXISTS primary_color text,
ADD COLUMN IF NOT EXISTS secondary_phone text,
ADD COLUMN IF NOT EXISTS social_instagram text,
ADD COLUMN IF NOT EXISTS social_tiktok text,
ADD COLUMN IF NOT EXISTS social_facebook text,
ADD COLUMN IF NOT EXISTS social_twitter text,
ADD COLUMN IF NOT EXISTS social_youtube text,
ADD COLUMN IF NOT EXISTS address_line2 text,
ADD COLUMN IF NOT EXISTS borough_id uuid REFERENCES public.boroughs(id),
ADD COLUMN IF NOT EXISTS neighborhood_id uuid REFERENCES public.neighborhoods(id),
ADD COLUMN IF NOT EXISTS business_model text,
ADD COLUMN IF NOT EXISTS operating_region text,
ADD COLUMN IF NOT EXISTS opening_date date,
ADD COLUMN IF NOT EXISTS internal_notes text,
ADD COLUMN IF NOT EXISTS use_crm boolean DEFAULT true,
ADD COLUMN IF NOT EXISTS use_route_planner boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS use_inventory boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS use_affiliates boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS use_ai_companion boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS use_store_master boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS require_brand_stores boolean DEFAULT false;