
create table if not exists sbo_polymarket_markets (
  id uuid primary key default gen_random_uuid(),
  condition_id text unique not null,
  question text not null,
  description text,
  category text default 'nba',
  game_id uuid references sbo_games(id),
  market_type text,
  home_team text,
  away_team text,
  player_name text,
  prop_type text,
  prop_line numeric,
  token_yes_price numeric,
  token_no_price numeric,
  token_home_price numeric,
  token_away_price numeric,
  token_over_price numeric,
  token_under_price numeric,
  volume_24h numeric default 0,
  volume_total numeric default 0,
  liquidity numeric default 0,
  open_interest numeric default 0,
  implied_prob_yes numeric,
  implied_prob_home numeric,
  implied_prob_over numeric,
  is_active boolean default true,
  end_date timestamptz,
  resolution text,
  resolved_at timestamptz,
  tokens jsonb default '[]',
  raw_data jsonb,
  fetched_at timestamptz default now(),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists sbo_odds_comparison (
  id uuid primary key default gen_random_uuid(),
  game_id uuid references sbo_games(id),
  prop_id uuid references sbo_player_props(id),
  comparison_date date not null default current_date,
  market_type text not null,
  outcome text not null,
  polymarket_prob numeric,
  polymarket_volume numeric,
  draftkings_prob numeric,
  fanduel_prob numeric,
  betmgm_prob numeric,
  caesars_prob numeric,
  sportsdata_prob numeric,
  avg_sportsbook_prob numeric,
  max_divergence numeric,
  polymarket_vs_books numeric,
  has_value boolean default false,
  value_direction text,
  edge_pct numeric,
  notes text,
  created_at timestamptz default now()
);

create table if not exists sbo_model_performance (
  id uuid primary key default gen_random_uuid(),
  evaluation_date date not null,
  brain_config jsonb not null,
  stats_weight numeric default 0.40,
  market_weight numeric default 0.35,
  context_weight numeric default 0.25,
  polymarket_weight numeric default 0.00,
  total_predictions integer default 0,
  correct_predictions integer default 0,
  accuracy_pct numeric default 0,
  elite_accuracy numeric,
  strong_accuracy numeric,
  moderate_accuracy numeric,
  weak_accuracy numeric,
  moneyline_accuracy numeric,
  props_accuracy numeric,
  avg_confidence_given numeric,
  avg_accuracy_achieved numeric,
  calibration_score numeric,
  is_active boolean default false,
  created_at timestamptz default now()
);

create table if not exists sbo_weight_history (
  id uuid primary key default gen_random_uuid(),
  adjusted_at timestamptz default now(),
  reason text not null,
  stats_weight_before numeric,
  market_weight_before numeric,
  context_weight_before numeric,
  polymarket_weight_before numeric,
  stats_weight_after numeric,
  market_weight_after numeric,
  context_weight_after numeric,
  polymarket_weight_after numeric,
  predictions_analyzed integer,
  accuracy_before numeric,
  accuracy_after_projected numeric,
  auto_adjusted boolean default false
);

create table if not exists sbo_line_movement (
  id uuid primary key default gen_random_uuid(),
  game_id uuid references sbo_games(id),
  prop_id uuid references sbo_player_props(id),
  market_type text not null,
  sportsbook text not null,
  outcome text not null,
  opening_odds integer,
  opening_implied_prob numeric,
  opening_recorded_at timestamptz,
  current_odds integer,
  current_implied_prob numeric,
  movement_cents integer,
  movement_direction text,
  is_steam_move boolean default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
