CREATE OR REPLACE FUNCTION public.automation_job_guard()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
DECLARE
  allowed text[];
BEGIN
  NEW.updated_at := now();
  IF TG_OP = 'UPDATE' AND NEW.status IS DISTINCT FROM OLD.status THEN
    allowed := CASE OLD.status
      WHEN 'CREATED'           THEN ARRAY['QUEUED','CANCELLED','NEEDS_INFORMATION','FAILED']
      WHEN 'QUEUED'            THEN ARRAY['STARTING','CANCELLED','NEEDS_INFORMATION','FAILED','BLOCKED']
      WHEN 'STARTING'          THEN ARRAY['RUNNING','FAILED','BLOCKED','CANCELLED','NEEDS_HUMAN_REVIEW']
      WHEN 'RUNNING'           THEN ARRAY['FORM_DETECTED','SUBMITTING','READING_RESPONSE','HUMAN_CHECKPOINT','FAILED','BLOCKED','NEEDS_INFORMATION','NEEDS_HUMAN_REVIEW','CANCELLED']
      WHEN 'FORM_DETECTED'     THEN ARRAY['FILLING','NEEDS_INFORMATION','FAILED','BLOCKED','NEEDS_HUMAN_REVIEW','CANCELLED']
      WHEN 'FILLING'           THEN ARRAY['DOCUMENT_UPLOAD','HUMAN_CHECKPOINT','READY_TO_SUBMIT','NEEDS_INFORMATION','FAILED','BLOCKED','NEEDS_HUMAN_REVIEW','CANCELLED']
      WHEN 'DOCUMENT_UPLOAD'   THEN ARRAY['HUMAN_CHECKPOINT','READY_TO_SUBMIT','NEEDS_INFORMATION','FAILED','BLOCKED','NEEDS_HUMAN_REVIEW','CANCELLED']
      WHEN 'HUMAN_CHECKPOINT'  THEN ARRAY['FILLING','DOCUMENT_UPLOAD','READY_TO_SUBMIT','SUBMITTING','NEEDS_HUMAN_REVIEW','FAILED','BLOCKED','CANCELLED']
      WHEN 'READY_TO_SUBMIT'   THEN ARRAY['SUBMITTING','HUMAN_CHECKPOINT','CANCELLED','FAILED','NEEDS_HUMAN_REVIEW']
      WHEN 'SUBMITTING'        THEN ARRAY['READING_RESPONSE','NEEDS_HUMAN_REVIEW','FAILED','BLOCKED']
      WHEN 'READING_RESPONSE'  THEN ARRAY['COMPLETED','NEEDS_HUMAN_REVIEW','FAILED']
      -- Manual submissions park in NEEDS_INFORMATION with human_action_type
      -- MANUAL_SUBMISSION; the operator's human checkpoint is a legal next step.
      WHEN 'NEEDS_INFORMATION' THEN ARRAY['QUEUED','HUMAN_CHECKPOINT','CANCELLED','FAILED']
      WHEN 'NEEDS_HUMAN_REVIEW'THEN ARRAY['QUEUED','COMPLETED','CANCELLED','FAILED']
      WHEN 'BLOCKED'           THEN ARRAY['NEEDS_HUMAN_REVIEW','CANCELLED','FAILED']
      WHEN 'FAILED'            THEN ARRAY['QUEUED','CANCELLED']
      ELSE ARRAY[]::text[]
    END;
    IF NOT (NEW.status = ANY(allowed)) THEN
      RAISE EXCEPTION 'Invalid automation job transition: % -> %', OLD.status, NEW.status;
    END IF;
    NEW.last_event_at := now();
  END IF;
  RETURN NEW;
END;
$$;