
-- FIX event_halls table
ALTER TABLE event_halls 
ADD COLUMN IF NOT EXISTS contact_email TEXT,
ADD COLUMN IF NOT EXISTS contact_name TEXT,
ADD COLUMN IF NOT EXISTS contact_phone TEXT,
ADD COLUMN IF NOT EXISTS hall_name TEXT,
ADD COLUMN IF NOT EXISTS tagline TEXT,
ADD COLUMN IF NOT EXISTS zip_code TEXT,
ADD COLUMN IF NOT EXISTS capacity_min INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS capacity_max INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS price_per_hour DECIMAL DEFAULT 0,
ADD COLUMN IF NOT EXISTS price_per_day DECIMAL DEFAULT 0,
ADD COLUMN IF NOT EXISTS instagram_handle TEXT,
ADD COLUMN IF NOT EXISTS website_url TEXT,
ADD COLUMN IF NOT EXISTS amenities TEXT[] DEFAULT '{}',
ADD COLUMN IF NOT EXISTS event_types TEXT[] DEFAULT '{}',
ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'pending';

-- FIX staff_members_ut table
ALTER TABLE staff_members_ut
ADD COLUMN IF NOT EXISTS available_states TEXT[] DEFAULT '{}',
ADD COLUMN IF NOT EXISTS contact_email TEXT,
ADD COLUMN IF NOT EXISTS contact_phone TEXT,
ADD COLUMN IF NOT EXISTS tagline TEXT,
ADD COLUMN IF NOT EXISTS role_category TEXT,
ADD COLUMN IF NOT EXISTS skills TEXT[] DEFAULT '{}',
ADD COLUMN IF NOT EXISTS years_experience INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS price_per_hour DECIMAL DEFAULT 0,
ADD COLUMN IF NOT EXISTS price_per_event DECIMAL DEFAULT 0,
ADD COLUMN IF NOT EXISTS price_type TEXT,
ADD COLUMN IF NOT EXISTS instagram_handle TEXT,
ADD COLUMN IF NOT EXISTS tiktok_handle TEXT,
ADD COLUMN IF NOT EXISTS languages_spoken TEXT[] DEFAULT '{}',
ADD COLUMN IF NOT EXISTS travel_willing BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'pending';
